# utils/languages.py
LANGUAGES = {
    'en': {
        'name': 'English',
        'direction': 'ltr',
        'states': {
            'Punjab': 'Punjab',
            'Haryana': 'Haryana', 
            'Uttar Pradesh': 'Uttar Pradesh',
            'Maharashtra': 'Maharashtra',
            'Karnataka': 'Karnataka',
            'Tamil Nadu': 'Tamil Nadu',
            'Andhra Pradesh': 'Andhra Pradesh',
            'Gujarat': 'Gujarat',
            'Odisha': 'Odisha',
            'Jharkhand': 'Jharkhand',
            'West Bengal': 'West Bengal',
            'Bihar': 'Bihar'
        },
        'ui': {
            'app_name': 'VARUN AI',
            'tagline': 'Vikasit Adhunik Roopantaran ke liye Uttam Nirdesh',
            'farmer_details': 'Farmer Details',
            'full_name': 'Full Name',
            'region': 'Region',
            'farm_size': 'Farm Size (acres)',
            'soil_properties': 'Soil Properties',
            'soil_type': 'Soil Type',
            'soil_ph': 'Soil pH',
            'soil_moisture': 'Soil Moisture (%)',
            'nitrogen': 'Nitrogen (kg/ha)',
            'phosphorus': 'Phosphorus (kg/ha)',
            'potassium': 'Potassium (kg/ha)',
            'environmental_factors': 'Environmental Factors',
            'temperature': 'Temperature (°C)',
            'rainfall': 'Annual Rainfall (mm)',
            'humidity': 'Humidity (%)',
            'analyze_button': 'Analyze & Recommend',
            'dashboard': 'Dashboard',
            'crop_recommendation': 'Crop Recommendation',
            'soil_analysis': 'Soil Analysis',
            'weather_forecast': 'Weather Forecast',
            'farm_overview': 'Farm Overview',
            'soil_nutrient_levels': 'Soil Nutrient Levels',
            'recommended_crop': 'Recommended Crop',
            'expected_yield': 'Expected Yield',
            'success_probability': 'Success Probability',
            'why_this_crop': 'Why this crop?',
            'planting_guide': 'Planting Guide',
            'best_planting_time': 'Best Planting Time',
            'water_requirements': 'Water Requirements',
            'fertilizer_recommendations': 'Fertilizer Recommendations',
            'harvest_timeline': 'Harvest Timeline',
            'market_insights': 'Market Insights',
            'current_market_price': 'Current market price',
            'demand_trend': 'Demand trend',
            'click_to_analyze': 'Click the button to get crop recommendations',
            'ph_level': 'pH Level',
            'moisture': 'Moisture',
            'organic_matter': 'Organic Matter',
            'wind_speed': 'Wind Speed',
            'created_by': 'Created with love by',
            'team_name': 'Team AgroNova',
            'for_sih': 'for SIH 2025',
            'language': 'Language',
            'select_language': 'Select Language'
        },
        'crops': {
            'Wheat': 'Wheat',
            'Rice': 'Rice',
            'Maize': 'Maize',
            'Cotton': 'Cotton',
            'Soybean': 'Soybean',
            'Pulses': 'Pulses'
        }
    },
    'hi': {
        'name': 'हिंदी',
        'direction': 'ltr',
        'states': {
            'Punjab': 'पंजाब',
            'Haryana': 'हरियाणा',
            'Uttar Pradesh': 'उत्तर प्रदेश',
            'Maharashtra': 'महाराष्ट्र',
            'Karnataka': 'कर्नाटक',
            'Tamil Nadu': 'तमिलनाडु',
            'Andhra Pradesh': 'आंध्र प्रदेश',
            'Gujarat': 'गुजरात',
            'Odisha': 'ओडिशा',
            'Jharkhand': 'झारखंड',
            'West Bengal': 'पश्चिम बंगाल',
            'Bihar': 'बिहार'
        },
        'ui': {
            'app_name': 'VARUN AI',
            'tagline': 'विकसित आधुनिक रूपांतरण के लिए उत्तम निर्देश',
            'farmer_details': 'किसान विवरण',
            'full_name': 'पूरा नाम',
            'region': 'क्षेत्र',
            'farm_size': 'खेत का आकार (एकड़)',
            'soil_properties': 'मिट्टी के गुण',
            'soil_type': 'मिट्टी का प्रकार',
            'soil_ph': 'मिट्टी का pH',
            'soil_moisture': 'मिट्टी की नमी (%)',
            'nitrogen': 'नाइट्रोजन (kg/ha)',
            'phosphorus': 'फॉस्फोरस (kg/ha)',
            'potassium': 'पोटैशियम (kg/ha)',
            'environmental_factors': 'पर्यावरणीय कारक',
            'temperature': 'तापमान (°C)',
            'rainfall': 'वार्षिक वर्षा (mm)',
            'humidity': 'आर्द्रता (%)',
            'analyze_button': 'विश्लेषण करें और सिफारिश करें',
            'dashboard': 'डैशबोर्ड',
            'crop_recommendation': 'फसल सिफारिश',
            'soil_analysis': 'मिट्टी विश्लेषण',
            'weather_forecast': 'मौसम पूर्वानुमान',
            'farm_overview': 'खेत का अवलोकन',
            'soil_nutrient_levels': 'मिट्टी के पोषक तत्वों के स्तर',
            'recommended_crop': 'सिफारिश की गई फसल',
            'expected_yield': 'अनुमानित उपज',
            'success_probability': 'सफलता की संभावना',
            'why_this_crop': 'यह फसल क्यों?',
            'planting_guide': 'रोपण मार्गदर्शिका',
            'best_planting_time': 'सर्वोत्तम रोपण समय',
            'water_requirements': 'पानी की आवश्यकताएं',
            'fertilizer_recommendations': 'उर्वरक सिफारिशें',
            'harvest_timeline': 'फसल कटाई की समयसीमा',
            'market_insights': 'बाजार की जानकारी',
            'current_market_price': 'वर्तमान बाजार मूल्य',
            'demand_trend': 'मांग की प्रवृत्ति',
            'click_to_analyze': 'फसल सिफारिशें प्राप्त करने के लिए बटन पर क्लिक करें',
            'ph_level': 'pH स्तर',
            'moisture': 'नमी',
            'organic_matter': 'कार्बनिक पदार्थ',
            'wind_speed': 'हवा की गति',
            'created_by': 'प्यार से बनाया गया',
            'team_name': 'टीम एग्रोनोवा',
            'for_sih': 'एसआईएच 2025 के लिए',
            'language': 'भाषा',
            'select_language': 'भाषा चुनें'
        },
        'crops': {
            'Wheat': 'गेहूं',
            'Rice': 'चावल',
            'Maize': 'मक्का',
            'Cotton': 'कपास',
            'Soybean': 'सोयाबीन',
            'Pulses': 'दलहन'
        }
    },
    'or': {
        'name': 'ଓଡିଆ',
        'direction': 'ltr',
        'states': {
            'Punjab': 'ପଞ୍ଜାବ',
            'Haryana': 'ହରିୟାଣା',
            'Uttar Pradesh': 'ଉତ୍ତର ପ୍ରଦେଶ',
            'Maharashtra': 'ମହାରାଷ୍ଟ୍ର',
            'Karnataka': 'କର୍ଣାଟକ',
            'Tamil Nadu': 'ତାମିଲନାଡୁ',
            'Andhra Pradesh': 'ଆନ୍ଧ୍ର ପ୍ରଦେଶ',
            'Gujarat': 'ଗୁଜରାଟ',
            'Odisha': 'ଓଡିଶା',
            'Jharkhand': 'ଝାଡଖଣ୍ଡ',
            'West Bengal': 'ପଶ୍ଚିମ ବଙ୍ଗ',
            'Bihar': 'ବିହାର'
        },
        'ui': {
            'app_name': 'VARUN AI',
            'tagline': 'ବିକଶିତ ଆଧୁନିକ ରୂପାନ୍ତରଣ ପାଇଁ ଉତ୍ତମ ନିର୍ଦେଶ',
            'farmer_details': 'କୃଷକର ବିବରଣୀ',
            'full_name': 'ପୂରା ନାମ',
            'region': 'ଅଞ୍ଚଳ',
            'farm_size': 'ଚାଷ ଜମିର ଆକାର (ଏକର)',
            'soil_properties': 'ମୃତ୍ତିକାର ଗୁଣ',
            'soil_type': 'ମୃତ୍ତିକାର ପ୍ରକାର',
            'soil_ph': 'ମୃତ୍ତିକାର pH',
            'soil_moisture': 'ମୃତ୍ତିକାର ଆର୍ଦ୍ରତା (%)',
            'nitrogen': 'ନାଇଟ୍ରୋଜେନ୍ (kg/ha)',
            'phosphorus': 'ଫସଫରସ୍ (kg/ha)',
            'potassium': 'ପଟାସିଅମ୍ (kg/ha)',
            'environmental_factors': 'ପରିବେଶଗତ କାରକ',
            'temperature': 'ତାପମାତ୍ରା (°C)',
            'rainfall': 'ବାର୍ଷିକ ବର୍ଷା (mm)',
            'humidity': 'ଆର୍ଦ୍ରତା (%)',
            'analyze_button': 'ବିଶ୍ଳେଷଣ କର ଏବଂ ପରାମର୍ଶ ଦିଅ',
            'dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
            'crop_recommendation': 'ଫସଲ ପରାମର୍ଶ',
            'soil_analysis': 'ମୃତ୍ତିକା ବିଶ୍ଳେଷଣ',
            'weather_forecast': 'ପାଣିପାଗ ପୂର୍ବାନୁମାନ',
            'farm_overview': 'ଚାଷ ଜମିର ସମୀକ୍ଷା',
            'soil_nutrient_levels': 'ମୃତ୍ତିକାର ପୋଷକ ତତ୍ତ୍ୱର ସ୍ତର',
            'recommended_crop': 'ପରାମର୍ଶିତ ଫସଲ',
            'expected_yield': 'ଆଶାକୃତ ଉତ୍ପାଦନ',
            'success_probability': 'ସଫଳତାର ସମ୍ଭାବନା',
            'why_this_crop': 'ଏହି ଫସଲ କାହିଁକି?',
            'planting_guide': 'ରୋପଣ ମାର୍ଗଦର୍ଶିକା',
            'best_planting_time': 'ସର୍ବୋତ୍ତମ ରୋପଣ ସମୟ',
            'water_requirements': 'ଜଳ ଆବଶ୍ୟକତା',
            'fertilizer_recommendations': 'ସାର ପରାମର୍ଶ',
            'harvest_timeline': 'ଫସଲ କଟାଇ ସମୟସୀମା',
            'market_insights': 'ବଜାରର ଅନ୍ତର୍ଦୃଷ୍ଟି',
            'current_market_price': 'ବର୍ତ୍ତମାନର ବଜାର ମୂଲ୍ୟ',
            'demand_trend': 'ଚାହିଦା ପ୍ରବୃତ୍ତି',
            'click_to_analyze': 'ଫସଲ ପରାମର୍ଶ ପାଇବା ପାଇଁ ବଟନ୍ ଦବାନ୍ତୁ',
            'ph_level': 'pH ସ୍ତର',
            'moisture': 'ଆର୍ଦ୍ରତା',
            'organic_matter': 'ଜୈବିକ ପଦାର୍ଥ',
            'wind_speed': 'ପବନର ଗତି',
            'created_by': 'ଭାଲୋବାସା କରି ତିଆରି କରାଯାଇଛି',
            'team_name': 'ଦଳ ଆଗ୍ରୋନୋଭା',
            'for_sih': 'SIH 2025 ପାଇଁ',
            'language': 'ଭାଷା',
            'select_language': 'ଭାଷା ଚୟନ କରନ୍ତୁ'
        },
        'crops': {
            'Wheat': 'ଗହମ',
            'Rice': 'ଚାଉଳ',
            'Maize': 'ମକା',
            'Cotton': 'କପାହ',
            'Soybean': 'ସୋୟାବିନ',
            'Pulses': 'ଡାଲି'
        }
    },
    'ta': {
        'name': 'தமிழ்',
        'direction': 'ltr',
        'states': {
            'Punjab': 'பஞ்சாப்',
            'Haryana': 'ஹரியானா',
            'Uttar Pradesh': 'உத்தரப் பிரதேசம்',
            'Maharashtra': 'மகாராஷ்டிரா',
            'Karnataka': 'கர்நாடகா',
            'Tamil Nadu': 'தமிழ்நாடு',
            'Andhra Pradesh': 'ஆந்திரப் பிரதேசம்',
            'Gujarat': 'குஜராத்',
            'Odisha': 'ஒடிசா',
            'Jharkhand': 'ஜார்கண்ட்',
            'West Bengal': 'மேற்கு வங்காளம்',
            'Bihar': 'பீகார்'
        },
        'ui': {
            'app_name': 'VARUN AI',
            'tagline': 'மேம்பட்ட நவீன மாற்றத்திற்கான சிறந்த வழிகாட்டி',
            'farmer_details': 'விவசாயி விவரங்கள்',
            'full_name': 'முழு பெயர்',
            'region': 'பிராந்தியம்',
            'farm_size': 'விவசாய நில அளவு (ஏக்கர்)',
            'soil_properties': 'மண் பண்புகள்',
            'soil_type': 'மண் வகை',
            'soil_ph': 'மண் pH',
            'soil_moisture': 'மண் ஈரப்பதம் (%)',
            'nitrogen': 'நைட்ரஜன் (kg/ha)',
            'phosphorus': 'பாஸ்பரஸ் (kg/ha)',
            'potassium': 'பொட்டாசியம் (kg/ha)',
            'environmental_factors': 'சுற்றுச்சூழல் காரணிகள்',
            'temperature': 'வெப்பநிலை (°C)',
            'rainfall': 'ஆண்டு மழை (mm)',
            'humidity': 'ஈரப்பதம் (%)',
            'analyze_button': 'பகுப்பாய்வு செய்து பரிந்துரைக்கவும்',
            'dashboard': 'டாஷ்போர்டு',
            'crop_recommendation': 'பயிர் பரிந்துரை',
            'soil_analysis': 'மண் பகுப்பாய்வு',
            'weather_forecast': 'வானிலை முன்னறிவிப்பு',
            'farm_overview': 'விவசாய நிலை மேலோட்டம்',
            'soil_nutrient_levels': 'மண் ஊட்டச்சத்து அளவுகள்',
            'recommended_crop': 'பரிந்துரைக்கப்பட்ட பயிர்',
            'expected_yield': 'எதிர்பார்க்கப்படும் விளைச்சல்',
            'success_probability': 'வெற்றி நிகழ்தகவு',
            'why_this_crop': 'இந்த பயிர் ஏன்?',
            'planting_guide': 'நடவு வழிகாட்டி',
            'best_planting_time': 'சிறந்த நடவு நேரம்',
            'water_requirements': 'நீர் தேவைகள்',
            'fertilizer_recommendations': 'உர பரிந்துரைகள்',
            'harvest_timeline': 'அறுவடை காலக்கெடு',
            'market_insights': 'சந்தை நுண்ணறிவுகள்',
            'current_market_price': 'தற்போதைய சந்தை விலை',
            'demand_trend': 'தேவைப் போக்கு',
            'click_to_analyze': 'பயிர் பரிந்துரைகளைப் பெற பொத்தானைக் கிளிக் செய்யவும்',
            'ph_level': 'pH அளவு',
            'moisture': 'ஈரப்பதம்',
            'organic_matter': 'கரிமப் பொருள்',
            'wind_speed': 'காற்றின் வேகம்',
            'created_by': 'அன்போடு உருவாக்கப்பட்டது',
            'team_name': 'டீம் அக்ரோநோவா',
            'for_sih': 'SIH 2025க்காக',
            'language': 'மொழி',
            'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்'
        },
        'crops': {
            'Wheat': 'கோதுமை',
            'Rice': 'நெல்',
            'Maize': 'சோளம்',
            'Cotton': 'பருத்தி',
            'Soybean': 'சோயா',
            'Pulses': 'பருப்பு வகைகள்'
        }
    },
    'bn': {
        'name': 'বাংলা',
        'direction': 'ltr',
        'states': {
            'Punjab': 'পঞ্জাব',
            'Haryana': 'হরিয়ানা',
            'Uttar Pradesh': 'উত্তর প্রদেশ',
            'Maharashtra': 'মহারাষ্ট্র',
            'Karnataka': 'কর্ণাটক',
            'Tamil Nadu': 'তামিলনাড়ু',
            'Andhra Pradesh': 'অন্ধ্র প্রদেশ',
            'Gujarat': 'গুজরাট',
            'Odisha': 'ওড়িশা',
            'Jharkhand': 'ঝাড়খণ্ড',
            'West Bengal': 'পশ্চিমবঙ্গ',
            'Bihar': 'বিহার'
        },
        'ui': {
            'app_name': 'VARUN AI',
            'tagline': 'উন্নত আধুনিক রূপান্তরের জন্য সেরা নির্দেশিকা',
            'farmer_details': 'কৃষকের বিবরণ',
            'full_name': 'পুরো নাম',
            'region': 'অঞ্চল',
            'farm_size': 'খামারের আকার (একর)',
            'soil_properties': 'মাটির বৈশিষ্ট্য',
            'soil_type': 'মাটির ধরন',
            'soil_ph': 'মাটির pH',
            'soil_moisture': 'মাটির আর্দ্রতা (%)',
            'nitrogen': 'নাইট্রোজেন (kg/ha)',
            'phosphorus': 'ফসফরাস (kg/ha)',
            'potassium': 'পটাসিয়াম (kg/ha)',
            'environmental_factors': 'পরিবেশগত কারণ',
            'temperature': 'তাপমাত্রা (°C)',
            'rainfall': 'বার্ষিক বৃষ্টিপাত (mm)',
            'humidity': 'আর্দ্রতা (%)',
            'analyze_button': 'বিশ্লেষণ করুন এবং সুপারিশ করুন',
            'dashboard': 'ড্যাশবোর্ড',
            'crop_recommendation': 'ফসল সুপারিশ',
            'soil_analysis': 'মাটির বিশ্লেষণ',
            'weather_forecast': 'আবহাওয়ার পূর্বাভাস',
            'farm_overview': 'খামারের ওভারভিউ',
            'soil_nutrient_levels': 'মাটির পুষ্টির মাত্রা',
            'recommended_crop': 'সুপারিশকৃত ফসল',
            'expected_yield': 'প্রত্যাশিত ফলন',
            'success_probability': 'সাফল্যের সম্ভাবনা',
            'why_this_crop': 'এই ফসল কেন?',
            'planting_guide': 'রোপণ গাইড',
            'best_planting_time': 'সেরা রোপণের সময়',
            'water_requirements': 'পানির প্রয়োজনীয়তা',
            'fertilizer_recommendations': 'সার সুপারিশ',
            'harvest_timeline': 'ফসল কাটার সময়সীমা',
            'market_insights': 'বাজার অন্তর্দৃষ্টি',
            'current_market_price': 'বর্তমান বাজার মূল্য',
            'demand_trend': 'চাহিদার প্রবণতা',
            'click_to_analyze': 'ফসলের সুপারিশ পেতে বাটন ক্লিক করুন',
            'ph_level': 'pH মাত্রা',
            'moisture': 'আর্দ্রতা',
            'organic_matter': 'জৈব পদার্থ',
            'wind_speed': 'বাতাসের গতি',
            'created_by': 'ভালোবাসা সহ তৈরি',
            'team_name': 'টিম এগ্রোনোভা',
            'for_sih': 'SIH 2025 এর জন্য',
            'language': 'ভাষা',
            'select_language': 'ভাষা নির্বাচন করুন'
        },
        'crops': {
            'Wheat': 'গম',
            'Rice': 'ধান',
            'Maize': 'ভুট্টা',
            'Cotton': 'তুলা',
            'Soybean': 'সয়াবিন',
            'Pulses': 'ডাল'
        }
    },
    'mr': {
        'name': 'मराठी',
        'direction': 'ltr',
        'states': {
            'Punjab': 'पंजाब',
            'Haryana': 'हरियाणा',
            'Uttar Pradesh': 'उत्तर प्रदेश',
            'Maharashtra': 'महाराष्ट्र',
            'Karnataka': 'कर्नाटक',
            'Tamil Nadu': 'तमिळनाडू',
            'Andhra Pradesh': 'आंध्र प्रदेश',
            'Gujarat': 'गुजरात',
            'Odisha': 'ओडिशा',
            'Jharkhand': 'झारखंड',
            'West Bengal': 'पश्चिम बंगाल',
            'Bihar': 'बिहार'
        },
        'ui': {
            'app_name': 'VARUN AI',
            'tagline': 'विकसित आधुनिक रूपांतरणासाठी उत्तम मार्गदर्शन',
            'farmer_details': 'शेतकरी तपशील',
            'full_name': 'पूर्ण नाव',
            'region': 'प्रदेश',
            'farm_size': 'शेताचा आकार (एकर)',
            'soil_properties': 'मातीचे गुणधर्म',
            'soil_type': 'मातीचा प्रकार',
            'soil_ph': 'मातीचा pH',
            'soil_moisture': 'मातीची आर्द्रता (%)',
            'nitrogen': 'नायट्रोजन (kg/ha)',
            'phosphorus': 'फॉस्फरस (kg/ha)',
            'potassium': 'पोटॅशियम (kg/ha)',
            'environmental_factors': 'पर्यावरणीय घटक',
            'temperature': 'तापमान (°C)',
            'rainfall': 'वार्षिक पाऊस (mm)',
            'humidity': 'आर्द्रता (%)',
            'analyze_button': 'विश्लेषण करा आणि शिफारस करा',
            'dashboard': 'डॅशबोर्ड',
            'crop_recommendation': 'पीक शिफारस',
            'soil_analysis': 'माती विश्लेषण',
            'weather_forecast': 'हवामान अंदाज',
            'farm_overview': 'शेताचा आढावा',
            'soil_nutrient_levels': 'मातीतील पोषक द्रव्य पातळी',
            'recommended_crop': 'शिफारस केलेली पीक',
            'expected_yield': 'अपेक्षित उत्पादन',
            'success_probability': 'यशाची शक्यता',
            'why_this_crop': 'हे पीक का?',
            'planting_guide': 'लागवड मार्गदर्शक',
            'best_planting_time': 'उत्तम लागवडीची वेळ',
            'water_requirements': 'पाण्याची आवश्यकता',
            'fertilizer_recommendations': 'खत शिफारसी',
            'harvest_timeline': 'कापणी वेळरेषा',
            'market_insights': 'बाजारातील अंतर्दृष्टी',
            'current_market_price': 'सध्याचा बाजारभाव',
            'demand_trend': 'मागणीची प्रवृत्ती',
            'click_to_analyze': 'पीक शिफारसी मिळविण्यासाठी बटण क्लिक करा',
            'ph_level': 'pH पातळी',
            'moisture': 'आर्द्रता',
            'organic_matter': 'सेंद्रिय पदार्थ',
            'wind_speed': 'वाऱ्याची गती',
            'created_by': 'प्रेमाने तयार केले',
            'team_name': 'टीम अॅग्रोनोव्हा',
            'for_sih': 'SIH 2025 साठी',
            'language': 'भाषा',
            'select_language': 'भाषा निवडा'
        },
        'crops': {
            'Wheat': 'गहू',
            'Rice': 'तांदूळ',
            'Maize': 'मका',
            'Cotton': 'कापूस',
            'Soybean': 'सोयाबीन',
            'Pulses': 'डाळ'
        }
    }
}

# State to language mapping
STATE_LANGUAGE_MAPPING = {
    'Odisha': 'or',
    'Jharkhand': 'hi',
    'Bihar': 'hi',
    'Punjab': 'hi',
    'Haryana': 'hi',
    'Uttar Pradesh': 'hi',
    'West Bengal': 'bn',
    'Maharashtra': 'mr',
    'Tamil Nadu': 'ta',
    'Default': 'en'
}

def get_language_for_state(state):
    """Get the default language for a given state"""
    return STATE_LANGUAGE_MAPPING.get(state, STATE_LANGUAGE_MAPPING['Default'])

def get_available_languages():
    """Return list of available languages"""
    return list(LANGUAGES.keys())

def get_state_name(state, lang):
    """Get translated state name"""
    return LANGUAGES[lang]['states'].get(state, state)
